# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 02:55
from __future__ import unicode_literals

import aldryn_common.admin_fields.sortedm2m
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0018_auto_20160802_1852'),
        ('aldryn_newsblog', '0015_auto_20161208_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, default=None, help_text='Choose and order the authors for this article', related_name='articles', to='aldryn_people.Person'),
        ),
    ]
